"""asdfasdf

Revision ID: cec2f2b9775a
Revises: c6c1d8edeb78
Create Date: 2026-04-03 18:20:30.979311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec2f2b9775a'
down_revision: Union[str, Sequence[str], None] = 'c6c1d8edeb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('users', 'telegram_username')
    # ### end Alembic commands ###
